version: "2.4"
services:
  pingaccess-admin:
    image: ${REGISTRY}/pingaccess:${PINGACCESS_LATEST}-alpine-az11-${GIT_TAG}
    environment:
      - SERVER_PROFILE_ADMIN_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_ADMIN_PATH=pa-clustering/pingaccess-admin
      - SERVER_PROFILE_PARENT=ADMIN
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pa-clustering/pingaccess
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - PA_CONSOLE_HOST=pingaccess-admin
      - PING_IDENTITY_PASSWORD=2FederateM0re
    env_file:
      # Property file below provides common envrionment variables for all integration_tests.
      # run_integration.sh creates /tmp/integration_tests.properties at runtime.
      - /tmp/integration_tests.properties
    ports:
      - "9000:9000"
    tmpfs: /run/secrets
    networks:
      - pingnet-internal

  pingaccess:
    image: ${REGISTRY}/pingaccess:${PINGACCESS_LATEST}-alpine-az11-${GIT_TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pa-clustering/pingaccess
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - PA_CONSOLE_HOST=pingaccess-admin
      - PING_IDENTITY_PASSWORD=2FederateM0re
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-internal
    command: wait-for pingaccess-admin:9000 -t 150 -- entrypoint.sh start-server


  sut:
    image: ${DEPS}postman/newman
    entrypoint: ["/usr/bin/env"]
    command: sh -c "/tmp/wait-for pingaccess:3000 -t 900 -- newman run /tmp/collection.json --insecure --ignore-redirects"
    volumes:
      - ./pa-cluster.postman_collection.json:/tmp/collection.json
      - ./wait-for:/tmp/wait-for
    depends_on:
      - pingaccess
    networks:
      - pingnet-internal

networks:
    pingnet-internal:
